name: Lint

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'shared/**'
      - '.github/workflows/lint.yaml'
  pull_request:
    branches: [ main, develop ]

jobs:
  lint-project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'pnpm'
    - name: Install dependencies
      run: |
        pnpm install
    - name: Run linter
      run: pnpm run lint